name: Go

on: 
  push:
    tags:
    - '*'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: make release

    - name: Create Release
      uses: ncipollo/release-action@v1.8.6
      with:
          draft: false
          prerelease: false
          artifacts: "release/artifacts/*"
          token: ${{ secrets.GITHUB_TOKEN }}

